name: Uncrustify

on:
    issue_comment:
      # types: [created]

jobs:
    run_uncrustify:
      if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'Marie Kondo')
      runs-on: ubuntu-latest
      steps:
        - uses: xt0rted/pull-request-comment-branch@v1
          id: comment-branch
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v2
          with:
              path: repo
              ref: ${{ steps.comment-branch.outputs.head_ref }}
        - name: Style
          run: | 
            # Install Uncrustify
            git clone https://github.com/uncrustify/uncrustify.git --branch uncrustify-0.72.0 --single-branch uncrustify
            mkdir -p uncrustify/build
            cd uncrustify/build
            cmake -DCMAKE_INSTALL_PREFIX=../install ..
            cmake --build . --target install -- -j$(nproc)
            cd ../..
            export PATH=${PWD}/uncrustify/install/bin:$PATH
            # Exec Uncrustify
            cd repo
            curl -l https://raw.githubusercontent.com/eProsima/cpp-style/master/uncrustify.cfg -o uncrustify.cfg
            find . \( -name "*.cpp" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" \) -exec uncrustify -c uncrustify.cfg --replace --no-backup {} +
            # Commit
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git commit -am "Uncrustified"
            git push
